helmDefaults:
  wait: true
  atomic: true
  timeout: 300
---
repositories:
  - url: {{ .Values.HARBOR_HOST | toString }}/{{ .Values.HARBOR_PROJECT_NAME | toString }}
    name: {{ .Values.APPLICATION_NAME | toString }}
    username: 'robot$x10-archery+x10-archery'
    password: {{ requiredEnv "HARBOR_ROBOT_TOKEN" }}
    oci: true
---
environments:
  development:
  production:
---
releases:
  - name: "{{ .Values.APPLICATION_NAME }}"
    namespace: "{{ .Values.K8S_NAMESPACE }}"
    version: "{{ .Values.CHART_VERSION }}"
    createNamespace: false
    chart: "{{ .Values.APPLICATION_NAME }}/{{ .Values.APPLICATION_NAME }}-chart/{{ .Values.APPLICATION_NAME }}"
    values:
      - image:
          repository: "{{ .Values.HARBOR_HOST }}/{{ .Values.HARBOR_PROJECT_NAME }}/{{ .Values.APPLICATION_NAME }}"
          tag: "{{ .Values.IMAGE_TAG }}"
        imagePullSecrets:
          - name: "{{ .Values.SECRET_NAME }}"
      - "./x10archery-backend.yaml.gotmpl"